# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc14c23151658f98917cbe683363bb2194078c8f49a138c66008a365747eae054b1dfc3bb691f6096afc8c686372d603f63f0d5cf5cf7ceb25129bf4a64423d0

test:
  secret_key_base: c61a655bdb453de77ba5c75cc01231e6772f30ef348c46e4fdde035d49e52781262203c894b4d6b71f5e1f3ef5f70e187abb3fd3f61fb2d3e73f2217cc346b02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
